apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment-maven
  labels:
    app: app-java-maven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-java-maven
  template:
    metadata:
      labels:
        app: app-java-maven
    spec:
      containers:
      - name: app-java-maven
        image: educavalieri/application_dev
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-java-maven
spec:
  selector:
    app: app-java-maven
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  type: NodePort
