apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: app-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-java
  template:
    metadata:
      labels:
        app: app-java
    spec:
      containers:
      - name: app-java
        image: educavalieri/app-java:1.0
        ports:
        - containerPort: 8081
