pipeline {
    environment {
        registry = "YourDockerhubAccount/YourRepository"
        registryCredential = 'dockerhub_id'
        dockerImage = "educavalieri/java-application:1.0"
    }
    agent any
    
    stages {
        stage('Criar imagem Docker java-application'){
            steps{
                sh 'docker build -t educavalieri/java-application:1.0 -f lab-ambiente/jenkins/docker/Dockerfile .'
            }
        }    
        stage('Deploy our image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                    sh 'docker image push educavalieri/java-application:1.0'
                    }
                }
            }
        }
        stage('Deploy Kubernets') {
            steps{                
                sh 'kubectl apply -f lab-ambiente/jenkins/deploy/pod.yml'
            }
        }       
    }
}