pipeline {
    agent any
    stages {
        stage('Criar imagem Docker java-application'){
            steps{
                sh 'docker build -t educavalieri/java-application:1.0 ./docker/ .'
            }
        }
    }
}