Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
#  config.vm.network "public_network", ip: "192.168.15.10"
  config.vm.hostname = 'jenkins-application'
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.network "private_network", ip: "192.168.1.5"
  config.vm.network 'forwarded_port', guest: 8080, host: 8080, hostip: '127.0.0.1'
  config.vm.network 'forwarded_port', guest: 8081, host: 8081, hostip: '127.0.0.1'
  config.vm.network 'forwarded_port', guest: 8091, host: 8091, hostip: '127.0.0.1'
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
  end
  config.vm.provision "shell", path: "provision.sh"
end
