---
- name: Configurar servidor de aplicação Java
  hosts: app01

  user: vagrant
  become: yes

  vars:
    - dbhost: "db01"
    - dbname: "db01"
    - dbusername: "root"
    - dbpasword: "devopsmaonamassa"  
  tasks:
    - name: Configurar hosts lab Ansible
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}" 
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01
    - name: Adicionar usuario de app
      user:
        name: app
        comment: Usuario de aplicação
        uid: 500
    - name: Donwload do Mavem versão x
      get_url: 
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.1.0/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/apache-maven-3.1.0-bin.tar.gz
    - name: Unzip do pacote maven
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Instalação do Java
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: Criação de diretório app
      file: 
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: instalacao do git client
      yum:
        name: git
        state: latest
    - name: Clone do repositório Notes -app
      git:
        repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: /opt/notes
        clone: yes
        force: yes
    - name: Configurar arquivo de propriedades para a camada de banco de dados
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: Gerar pacotes da aplicação
      command: /opt/apache-maven-3.1.0/bin/mvn -f/opt/notes/pom.xml package
      become_user: app
    - name: Registrar versao atual do pacote
      shell:
        cmd: /opt/apache-maven-3.1.0/bin/mvn -o -q -Dexec.executable=echo -Dexec.args='${project.version}' exec:exec
        chdir: /opt/notes/
      register: app_version
    - name: Configurar Serviço do Systemd
      template:
        src: etc/systemd/system/notes.service
        src: /etc/systemd/system/notes.service
        notify: reload daemon
    - name: Iniciar Serviço notes
      service: 
        name: notes
        state: restarted
  roles:
    - configuracao-default-so
  handlers:
    - name: reload app
      systemd:
        state: restarted
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes


