apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-apache
  labels:
    app: app-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-apache
  template:
    metadata:
      labels:
        app: app-apache
    spec:
      containers:
      - name: app-apache
        image: httpd:latest
        ports:
        - containerPort: 80
