pipeline {
    environment {
        registry = "YourDockerhubAccount/YourRepository"
        registryCredential = 'dockerhub_id'
        dockerImage = "educavalieri/java-application:latest"
    }
    agent any
    tools{
        maven 'maven_3_9_6'
    }
     stages {
        stage('Build Maven'){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/educavalieri/application_devepos']])
                sh 'mvn clean install'
            }
        }
        stage('Build Docker image'){
            steps{
                script{
                    sh 'docker build -t educavalieri/application_dev .'
                }
            }
        }
        stage('Deploy our image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                    sh 'docker image push educavalieri/application_dev'
                    }
                }
            }
        }
        stage('Deploy Kubernets') {
            steps{                
                sh 'kubectl apply -f lab-ambiente/jenkins/deploy/pod.yml'
            }
        }                 
    }
}