Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = 'k3s'
  config.vm.network "private_network", ip: "192.168.1.5"
  config.vm.network 'forwarded_port', guest: 8081, host: 8081, hostip: '127.0.0.1'
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end

end
